output:
  base_dir: "test_impulse_per_batch_results"
  save_plots: true
  save_intermediate_results: true

base_data_dir: "data"

experiments:
  data_processing:
    enabled: true
  dimensionality_reduction:
    enabled: false
  discrimination_analysis:
    enabled: false
  feature_ablation:
    enabled: false
  impulse_response:
    enabled: true
  saliency_analysis:
    enabled: false
